spring:
  application:
    name: learner
  datasource:
    url: jdbc:postgresql://localhost:15432/learner_db
    username: myuser
    password: secret
  sql:
    init:
      mode: always
      schema-locations: classpath:db/01_schema.sql
      data-locations: classpath:db/02_seed.sql
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false