-- =============================================================
--  01_schema.sql — full application schema (PostgreSQL 14+)
--
--  Run order:  01_schema.sql -> 02_seed.sql
--  Companions (manual, run separately): seed_base.sql (language + demo
--  account only), wipe_all.sql (empty every table), wipe_except_basic.sql
--  (empty everything except language/account), clear_user_activity.sql
--  (empty only attempt/sessions/list_progress/user_list)
--
--  LAYERS
--    Language data (never written by the app; ingested):
--      language, lexeme, word_form, translation, list, list_item
--    User data (written by the app):
--      account, user_list, list_progress, sessions, attempt
--    learning_plan is COMPUTED on demand — not a table.
--
--  LOAD-BEARING RULES (see the per-table .md specs for rationale)
--    * One word = one lexeme + many word_form rows (store-vs-derive).
--      Irregular forms live in lexeme.tema (jsonb); regular forms derive
--      from infl_class. word_form is the expanded, queryable paradigm.
--    * translation is undirected pairwise between two lexeme rows, stored
--      once (CHECK lexeme_a < lexeme_b), read both directions.
--    * word_form.form_type is OPEN TEXT (inventories differ per language);
--      exercise_type IS a native enum (small, closed, app-controlled).
--    * Learning is list-scoped: list_progress keyed (user, list, lexeme).
--    * user_list is the ENROLLMENT and the parent of list_progress + sessions
--      (both FK their (user_id, list_id) to it).
--    * account holds the DEFAULT learning pair (catalog filter + enroll
--      pre-fill); user_list.base_lang is the per-enrollment truth.
--    * attempt is an append-only log, denormalized for query speed.
-- =============================================================
BEGIN;

DROP TABLE IF EXISTS attempt, sessions, list_progress, user_list, account,
                     list_item, list, translation, word_form, lexeme, language CASCADE;
DROP TYPE IF EXISTS exercise_type CASCADE;

-- Exercise types: small, closed, app-controlled -> native enum is appropriate.
-- (Contrast word_form.form_type, which is open text.)
CREATE TYPE exercise_type AS ENUM
  ('en_ett','assemble','translate','base_form','produce_form','multi_select');

-- =========================================================================
--  LANGUAGE DATA
-- =========================================================================

CREATE TABLE language (
    code char(2) PRIMARY KEY,          -- ISO 639-1: 'en', 'sv', ...
    name text NOT NULL
);

-- A word in ONE language. The arbitrary/irregular facts are stored here;
-- the full paradigm is derived into word_form.
CREATE TABLE lexeme (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lang       char(2) NOT NULL REFERENCES language(code),
    lemma      text    NOT NULL,
    citation   text,                        -- ready-to-display headword (att gå, ett hus, to go)
                                            -- composed by INGESTION per language; the server READS
                                            -- this, never composes articles/markers itself.
    pos        text    NOT NULL,           -- noun|verb|pronoun|number|adj|...
    gender     text,                        -- sv noun: 'en' | 'ett' (NULL elsewhere)
    infl_class text,                        -- inflection class (drives form generation)
    tema       jsonb   NOT NULL DEFAULT '{}', -- irregular principal parts only
    note       text,                        -- translation nuance ('to go, to walk')
    freq_rank  int,                         -- per-language frequency ordering
    UNIQUE (lang, lemma, pos)               -- homographs stay distinct via pos/gender
);
CREATE INDEX lexeme_lang_pos_idx ON lexeme (lang, pos);
CREATE INDEX lexeme_freq_idx     ON lexeme (lang, freq_rank);

-- Expanded, queryable paradigm. One row per inflected form.
-- form_type is OPEN TEXT (per-language inventories; catalog documented in word_form.md).
CREATE TABLE word_form (
    lexeme_id bigint NOT NULL REFERENCES lexeme(id) ON DELETE CASCADE,
    form_type text   NOT NULL,             -- 'indef_sg','preteritum','nom_sg',...
    form      text   NOT NULL,
    PRIMARY KEY (lexeme_id, form_type)
);
CREATE INDEX word_form_form_idx ON word_form (form);   -- token -> lexeme lookup

-- Undirected pairwise translation between two lexemes; stored once (a < b),
-- read in either direction.
CREATE TABLE translation (
    lexeme_a bigint NOT NULL REFERENCES lexeme(id) ON DELETE CASCADE,
    lexeme_b bigint NOT NULL REFERENCES lexeme(id) ON DELETE CASCADE,
    PRIMARY KEY (lexeme_a, lexeme_b),
    CHECK (lexeme_a < lexeme_b)
);
CREATE INDEX translation_b_idx ON translation (lexeme_b);  -- reverse-direction reads

-- A curated set of words to learn.
CREATE TABLE list (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              text    NOT NULL,
    target_lang       char(2) NOT NULL REFERENCES language(code),
    user_id           bigint,                 -- NULL = curated/global; set = generated (post-MVP)
    allowed_exercises exercise_type[]         -- NULL = all types permitted
);

CREATE TABLE list_item (
    list_id   bigint NOT NULL REFERENCES list(id)   ON DELETE CASCADE,
    lexeme_id bigint NOT NULL REFERENCES lexeme(id) ON DELETE CASCADE,
    position  int,                            -- curated ordering within the list
    PRIMARY KEY (list_id, lexeme_id)
);

-- =========================================================================
--  USER DATA
-- =========================================================================

-- Identity + the user's DEFAULT learning pair. The pair (learn_base_lang,
-- learn_target_lang) filters the catalog and pre-fills user_list.base_lang at
-- enroll time; it is NOT the learning truth (that is user_list.base_lang).
CREATE TABLE account (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email             text    NOT NULL UNIQUE,
    name              text,                                        -- display name (set at init_account)
    ui_lang           char(2) REFERENCES language(code) DEFAULT 'en', -- app UI language
    learn_base_lang   char(2) REFERENCES language(code),           -- default/filter: taught FROM
    learn_target_lang char(2) REFERENCES language(code),           -- default/filter: learning
    status            text    NOT NULL DEFAULT 'free',             -- 'free' | 'paid'
    created_at        timestamptz NOT NULL DEFAULT now()
);

-- ENROLLMENT: assigning a list = ONE row here (a reference, not a word copy).
-- base_lang = the language this list is learned FROM (pre-filled from the
-- account default pair). Parent of list_progress + sessions.
CREATE TABLE user_list (
    user_id      bigint  NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    list_id      bigint  NOT NULL REFERENCES list(id)    ON DELETE CASCADE,
    base_lang    char(2) NOT NULL REFERENCES language(code),
    status       text    NOT NULL DEFAULT 'active',           -- 'active' | 'completed'
    started_at   timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,
    PRIMARY KEY (user_id, list_id)
);

-- MVP: one ACTIVE list per user, enforced in application logic (switching lists
-- deletes the current enrollment, cascading to progress/sessions). Optional DB
-- hardening (uncomment to enforce):
-- CREATE UNIQUE INDEX one_active_enrollment ON user_list (user_id) WHERE status = 'active';

-- Per-word progress, keyed (user, list, lexeme). NOT shared across lists.
-- Created lazily on first practice; UPSERTed once per attempt. No row = not started.
CREATE TABLE list_progress (
    user_id         bigint NOT NULL,
    list_id         bigint NOT NULL,
    lexeme_id       bigint NOT NULL REFERENCES lexeme(id) ON DELETE CASCADE,
    times_practiced int NOT NULL DEFAULT 0,
    correct         int NOT NULL DEFAULT 0,
    wrong           int NOT NULL DEFAULT 0,
    due             timestamptz,
    PRIMARY KEY (user_id, list_id, lexeme_id),
    FOREIGN KEY (user_id, list_id) REFERENCES user_list(user_id, list_id) ON DELETE CASCADE
);
CREATE INDEX list_progress_due_idx ON list_progress (user_id, due);

-- Completed-session log. One row written when a session FINISHES (store the past,
-- estimate the future). Sessions are DERIVED on demand, never precomputed.
CREATE TABLE sessions (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint NOT NULL,
    list_id    bigint NOT NULL,
    started_at timestamptz NOT NULL,
    ended_at   timestamptz,
    FOREIGN KEY (user_id, list_id) REFERENCES user_list(user_id, list_id) ON DELETE CASCADE
);

-- Append-only log; one row per answered exercise; never updated. Denormalized
-- (individual FKs) for query speed. Source of truth for stats; list_progress is
-- a maintained summary derived from these. Intro cards are NOT logged here.
CREATE TABLE attempt (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       bigint NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    list_id       bigint NOT NULL REFERENCES list(id)    ON DELETE CASCADE,
    lexeme_id     bigint NOT NULL REFERENCES lexeme(id)  ON DELETE CASCADE,
    session_id    bigint REFERENCES sessions(id) ON DELETE SET NULL,
    exercise_type exercise_type NOT NULL,
    form_type     text,                         -- which form tested (NULL for whole-word)
    is_correct    boolean NOT NULL,
    elapsed_ms    int,
    created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX attempt_user_time_idx ON attempt (user_id, created_at);
CREATE INDEX attempt_word_idx      ON attempt (user_id, list_id, lexeme_id);

COMMIT;
