-- =============================================================
--  01_schema.sql   — vocabulary learning app (PostgreSQL 14+)
--  Run first, then 02_seed.sql
-- =============================================================
BEGIN;

DROP TABLE IF EXISTS review_log, user_sense_state, app_user,
                     aspect_pair, translation, sense, word_form,
                     lexeme, language CASCADE;

-- ---------- languages ----------
CREATE TABLE language (
    code char(2) PRIMARY KEY,
    name text NOT NULL
);

-- ---------- lexeme : one lemma in ONE language ----------
CREATE TABLE lexeme (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lang        char(2) NOT NULL REFERENCES language(code),
    lemma       text    NOT NULL,
    pos         text    NOT NULL,
    gender      text,                         -- sv noun: 'en' | 'ett'
    infl_class  text,                         -- 'ZERO','strong','weak1', ru decl class...
    aspect      text,                         -- ru verb: 'imperfective' | 'perfective'
    is_deponent boolean NOT NULL DEFAULT false,
    tema        jsonb   NOT NULL DEFAULT '{}',-- irregular parts only
    freq_rank   int,
    cefr        text,
    UNIQUE (lang, lemma, pos)
);
CREATE INDEX lexeme_lang_pos_idx ON lexeme (lang, pos);
CREATE INDEX lexeme_freq_idx     ON lexeme (lang, freq_rank);

-- ---------- word_form : derived, queryable inflected forms ----------
CREATE TABLE word_form (
    lexeme_id bigint NOT NULL REFERENCES lexeme(id) ON DELETE CASCADE,
    form_type text   NOT NULL,                -- OPEN-ENDED key
    form      text   NOT NULL,
    PRIMARY KEY (lexeme_id, form_type)
);
CREATE INDEX word_form_form_idx ON word_form (form);

-- ---------- sense : one meaning of one lexeme (in ITS language) ----------
CREATE TABLE sense (
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lexeme_id bigint NOT NULL REFERENCES lexeme(id) ON DELETE CASCADE,
    sense_num int    NOT NULL,
    gloss     text   NOT NULL,                -- in the sense's own language
    gloss_dev text,                           -- optional English dev label
    UNIQUE (lexeme_id, sense_num)
);

-- ---------- translation : directed, typed sense→sense edge ----------
CREATE TABLE translation (
    from_sense  bigint NOT NULL REFERENCES sense(id) ON DELETE CASCADE,
    to_sense    bigint NOT NULL REFERENCES sense(id) ON DELETE CASCADE,
    equivalence text   NOT NULL,
    usage_note  text,
    PRIMARY KEY (from_sense, to_sense),
    CHECK (from_sense <> to_sense),
    CHECK (equivalence IN ('exact','broader','narrower','approximate','none'))
);
CREATE INDEX translation_to_idx ON translation (to_sense);

-- ---------- aspect_pair : intra-language lexeme↔lexeme (Russian) ----------
CREATE TABLE aspect_pair (
    imperfective bigint NOT NULL REFERENCES lexeme(id) ON DELETE CASCADE,
    perfective   bigint NOT NULL REFERENCES lexeme(id) ON DELETE CASCADE,
    PRIMARY KEY (imperfective, perfective)
);

-- =============================================================
--  learning layer (created; seeded separately / by the app)
-- =============================================================
CREATE TABLE app_user (
    id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    l1     char(2) NOT NULL REFERENCES language(code),
    target char(2) NOT NULL REFERENCES language(code)
);

CREATE TABLE user_sense_state (
    user_id       bigint NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    sense_id      bigint NOT NULL REFERENCES sense(id)    ON DELETE CASCADE,
    stability     real,
    difficulty    real,
    due           timestamptz,
    last_reviewed timestamptz,
    reps          int NOT NULL DEFAULT 0,
    PRIMARY KEY (user_id, sense_id)
);
CREATE INDEX uss_due_idx ON user_sense_state (user_id, due);

CREATE TABLE review_log (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     bigint NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    sense_id    bigint NOT NULL REFERENCES sense(id)    ON DELETE CASCADE,
    reviewed_at timestamptz NOT NULL DEFAULT now(),
    rating      smallint NOT NULL,
    task_type   text,
    elapsed_ms  int
);
CREATE INDEX review_log_user_time_idx ON review_log (user_id, reviewed_at);

COMMIT;
