-- =============================================================
--  01_schema.sql — full app schema (PostgreSQL 14+)
--  Language data:  language, lexeme, word_form, translation, list, list_item
--  User data:      account, user_list, list_progress, sessions, attempt
--  Run first, then 02_seed.sql
--
--  CHANGE LOG (this revision):
--   1. sessions      -> composite FK (user_id, list_id) REFERENCES user_list
--   2. list_progress -> composite FK (user_id, list_id) REFERENCES user_list
--   3. account.base_lang  REMOVED
--   4. user_list.base_lang ADDED (taught-from language, per enrollment)
--   -  attempt stays denormalized (no composite FK) — append-only log, speed over
--      strict integrity; its (user,list) is reachable via session_id.
--   -  word_form.form_type stays open TEXT (not enum) — inventories differ per
--      language; the catalog lives in word_form.md as documentation only.
-- =============================================================
BEGIN;

DROP TABLE IF EXISTS attempt, sessions, list_progress, user_list, account,
                     list_item, list, translation, word_form, lexeme, language CASCADE;
DROP TYPE IF EXISTS exercise_type CASCADE;

-- exercise types: small, closed, app-controlled -> native enum is appropriate here
-- (contrast form_type, which is open text; see word_form.md).
CREATE TYPE exercise_type AS ENUM
  ('en_ett','assemble','translate','base_form','produce_form','multi_select');

-- =========================== LANGUAGE DATA ===========================

CREATE TABLE language (
    code char(2) PRIMARY KEY,
    name text NOT NULL
);

CREATE TABLE lexeme (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lang       char(2) NOT NULL REFERENCES language(code),
    lemma      text    NOT NULL,
    pos        text    NOT NULL,
    gender     text,                          -- sv noun: 'en' | 'ett'
    infl_class text,
    tema       jsonb   NOT NULL DEFAULT '{}', -- irregular principal parts only
    note       text,                          -- translation nuance ('to go, to walk')
    freq_rank  int,
    UNIQUE (lang, lemma, pos)
);
CREATE INDEX lexeme_lang_pos_idx ON lexeme (lang, pos);
CREATE INDEX lexeme_freq_idx     ON lexeme (lang, freq_rank);

-- expanded, queryable paradigm. form_type is OPEN TEXT (per-language inventories).
CREATE TABLE word_form (
    lexeme_id bigint NOT NULL REFERENCES lexeme(id) ON DELETE CASCADE,
    form_type text   NOT NULL,
    form      text   NOT NULL,
    PRIMARY KEY (lexeme_id, form_type)
);
CREATE INDEX word_form_form_idx ON word_form (form);

-- undirected pairwise; stored once (a < b), read both ways
CREATE TABLE translation (
    lexeme_a bigint NOT NULL REFERENCES lexeme(id) ON DELETE CASCADE,
    lexeme_b bigint NOT NULL REFERENCES lexeme(id) ON DELETE CASCADE,
    PRIMARY KEY (lexeme_a, lexeme_b),
    CHECK (lexeme_a < lexeme_b)
);
CREATE INDEX translation_b_idx ON translation (lexeme_b);

CREATE TABLE list (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              text    NOT NULL,
    target_lang       char(2) NOT NULL REFERENCES language(code),
    user_id           bigint,                 -- NULL = curated; reserved for gen lists
    allowed_exercises exercise_type[]         -- NULL = all types permitted
);

CREATE TABLE list_item (
    list_id   bigint NOT NULL REFERENCES list(id)   ON DELETE CASCADE,
    lexeme_id bigint NOT NULL REFERENCES lexeme(id) ON DELETE CASCADE,
    position  int,
    PRIMARY KEY (list_id, lexeme_id)
);

-- ============================= USER DATA =============================

-- (3) base_lang removed — the taught-from language is per-enrollment, not per-account.
CREATE TABLE account (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      text    NOT NULL UNIQUE,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- enrollment: assigning a list = ONE row here (a reference, not a word copy).
-- (4) base_lang added: learn this list's target_lang FROM base_lang.
CREATE TABLE user_list (
    user_id      bigint  NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    list_id      bigint  NOT NULL REFERENCES list(id)    ON DELETE CASCADE,
    base_lang    char(2) NOT NULL REFERENCES language(code),  -- taught-from language
    status       text    NOT NULL DEFAULT 'active',           -- 'active' | 'completed'
    started_at   timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,
    PRIMARY KEY (user_id, list_id)
);

-- (2) per-word progress; (user,list) FKs to the ENROLLMENT, not account+list.
CREATE TABLE list_progress (
    user_id         bigint NOT NULL,
    list_id         bigint NOT NULL,
    lexeme_id       bigint NOT NULL REFERENCES lexeme(id) ON DELETE CASCADE,
    times_practiced int NOT NULL DEFAULT 0,
    correct         int NOT NULL DEFAULT 0,
    wrong           int NOT NULL DEFAULT 0,
    due             timestamptz,
    PRIMARY KEY (user_id, list_id, lexeme_id),
    FOREIGN KEY (user_id, list_id) REFERENCES user_list(user_id, list_id) ON DELETE CASCADE
);
CREATE INDEX list_progress_due_idx ON list_progress (user_id, due);

-- (1) completed-session log; (user,list) FKs to the ENROLLMENT.
CREATE TABLE sessions (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint NOT NULL,
    list_id    bigint NOT NULL,
    started_at timestamptz NOT NULL,
    ended_at   timestamptz,
    FOREIGN KEY (user_id, list_id) REFERENCES user_list(user_id, list_id) ON DELETE CASCADE
);

-- append-only log; one row per answered exercise; never updated.
-- kept denormalized (individual FKs) for query speed; not re-parented to user_list.
CREATE TABLE attempt (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       bigint NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    list_id       bigint NOT NULL REFERENCES list(id)    ON DELETE CASCADE,
    lexeme_id     bigint NOT NULL REFERENCES lexeme(id)  ON DELETE CASCADE,
    session_id    bigint REFERENCES sessions(id) ON DELETE SET NULL,
    exercise_type exercise_type NOT NULL,
    form_type     text,                         -- which form tested (NULL for whole-word)
    is_correct    boolean NOT NULL,
    elapsed_ms    int,
    created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX attempt_user_time_idx ON attempt (user_id, created_at);
CREATE INDEX attempt_word_idx      ON attempt (user_id, list_id, lexeme_id);

COMMIT;
