-- =============================================================
--  seed_first50.sql — 50 concept pairs (sv<->en), THREE lists.
--    100 'Swedish first 50' (all 50)  101 'Basic nouns' (20)  102 'Basic verbs' (20)
--
--  POS-ALIGNED: every translation links same part of speech (noun<->noun,
--  verb<->verb, adj<->adj).
--  BOTH LANGUAGES ARE FULL TARGETS: sv AND en each carry infl_class, tema
--  (irregulars only) and a complete word_form paradigm — English can be learned
--  (e.g. from uk/ru), so it is no longer meaning-only.
--  citation is STORED (lexeme.citation); the server reads it, composes nothing.
--
--  IDEMPOTENT (ON CONFLICT DO NOTHING). Run AFTER 01_schema.sql. ids 1001+/lists 100-102.
-- =============================================================
BEGIN;

INSERT INTO language (code, name) VALUES ('sv','Swedish'),('en','English')
  ON CONFLICT (code) DO NOTHING;

-- ---------- Swedish lexemes ----------
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1001,'sv','pojke','en pojke','noun','en','AR','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1002,'sv','flicka','en flicka','noun','en','OR','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1003,'sv','mamma','en mamma','noun','en','OR','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1004,'sv','pappa','en pappa','noun','en','OR','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1005,'sv','bror','en bror','noun','en','irregular','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1006,'sv','syster','en syster','noun','en','AR','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1007,'sv','rum','ett rum','noun','ett','ZERO','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1008,'sv','kök','ett kök','noun','ett','ZERO','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1009,'sv','säng','en säng','noun','en','AR','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1010,'sv','klocka','en klocka','noun','en','OR','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1011,'sv','nyckel','en nyckel','noun','en','AR','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1012,'sv','väska','en väska','noun','en','OR','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1013,'sv','skola','en skola','noun','en','OR','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1014,'sv','arbete','ett arbete','noun','ett','N','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1015,'sv','affär','en affär','noun','en','ER','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1016,'sv','tåg','ett tåg','noun','ett','ZERO','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1017,'sv','flygplan','ett flygplan','noun','ett','ZERO','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1018,'sv','gata','en gata','noun','en','OR','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1019,'sv','sol','en sol','noun','en','AR','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1020,'sv','måne','en måne','noun','en','AR','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1021,'sv','komma','att komma','verb',NULL,'strong','{"present": "kommer", "preteritum": "kom", "supine": "kommit"}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1022,'sv','ge','att ge','verb',NULL,'strong','{"present": "ger", "preteritum": "gav", "supine": "gett"}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1023,'sv','ta','att ta','verb',NULL,'strong','{"present": "tar", "preteritum": "tog", "supine": "tagit"}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1024,'sv','se','att se','verb',NULL,'strong','{"present": "ser", "preteritum": "såg", "supine": "sett"}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1025,'sv','höra','att höra','verb',NULL,'weak2a','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1026,'sv','känna','att känna','verb',NULL,'weak2a','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1027,'sv','tänka','att tänka','verb',NULL,'weak2b','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1028,'sv','veta','att veta','verb',NULL,'irregular','{"present": "vet", "preteritum": "visste", "supine": "vetat"}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1029,'sv','förstå','att förstå','verb',NULL,'strong','{"present": "förstår", "preteritum": "förstod", "supine": "förstått"}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1030,'sv','fråga','att fråga','verb',NULL,'weak1','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1031,'sv','svara','att svara','verb',NULL,'weak1','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1032,'sv','hjälpa','att hjälpa','verb',NULL,'weak2b','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1033,'sv','vänta','att vänta','verb',NULL,'weak1','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1034,'sv','resa','att resa','verb',NULL,'weak2b','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1035,'sv','köra','att köra','verb',NULL,'weak2a','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1036,'sv','flyga','att flyga','verb',NULL,'strong','{"present": "flyger", "preteritum": "flög", "supine": "flugit"}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1037,'sv','simma','att simma','verb',NULL,'weak1','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1038,'sv','sjunga','att sjunga','verb',NULL,'strong','{"present": "sjunger", "preteritum": "sjöng", "supine": "sjungit"}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1039,'sv','dansa','att dansa','verb',NULL,'weak1','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1040,'sv','skratta','att skratta','verb',NULL,'weak1','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1041,'sv','lång','lång','adj',NULL,'regular','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1042,'sv','kort','kort','adj',NULL,'regular','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1043,'sv','hög','hög','adj',NULL,'regular','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1044,'sv','låg','låg','adj',NULL,'regular','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1045,'sv','tung','tung','adj',NULL,'regular','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1046,'sv','lätt','lätt','adj',NULL,'regular','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1047,'sv','stark','stark','adj',NULL,'regular','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1048,'sv','svag','svag','adj',NULL,'regular','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1049,'sv','vacker','vacker','adj',NULL,'irregular','{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,gender,infl_class,tema) VALUES (1050,'sv','ful','ful','adj',NULL,'regular','{}') ON CONFLICT (id) DO NOTHING;

-- ---------- English lexemes (full target: class + tema + citation) ----------
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1101,'en','boy','boy','noun','regular','{}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1102,'en','girl','girl','noun','regular','{}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1103,'en','mum','mum','noun','regular','{}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1104,'en','dad','dad','noun','regular','{}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1105,'en','brother','brother','noun','regular','{}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1106,'en','sister','sister','noun','regular','{}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1107,'en','room','room','noun','regular','{}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1108,'en','kitchen','kitchen','noun','regular','{}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1109,'en','bed','bed','noun','regular','{}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1110,'en','clock','clock','noun','regular','{}','clock, watch') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1111,'en','key','key','noun','regular','{}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1112,'en','bag','bag','noun','regular','{}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1113,'en','school','school','noun','regular','{}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1114,'en','work','work','noun','regular','{}','work, job') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1115,'en','shop','shop','noun','regular','{}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1116,'en','train','train','noun','regular','{}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1117,'en','aeroplane','aeroplane','noun','regular','{}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1118,'en','street','street','noun','regular','{}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1119,'en','sun','sun','noun','regular','{}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1120,'en','moon','moon','noun','regular','{}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1121,'en','come','to come','verb','irregular','{"preteritum": "came", "supine": "come"}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1122,'en','give','to give','verb','irregular','{"preteritum": "gave", "supine": "given"}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1123,'en','take','to take','verb','irregular','{"preteritum": "took", "supine": "taken"}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1124,'en','see','to see','verb','irregular','{"preteritum": "saw", "supine": "seen"}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1125,'en','hear','to hear','verb','irregular','{"preteritum": "heard", "supine": "heard"}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1126,'en','feel','to feel','verb','irregular','{"preteritum": "felt", "supine": "felt"}','feel, know a person') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1127,'en','think','to think','verb','irregular','{"preteritum": "thought", "supine": "thought"}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1128,'en','know','to know','verb','irregular','{"preteritum": "knew", "supine": "known"}','know a fact') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1129,'en','understand','to understand','verb','irregular','{"preteritum": "understood", "supine": "understood"}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1130,'en','ask','to ask','verb','regular','{}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1131,'en','answer','to answer','verb','regular','{}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1132,'en','help','to help','verb','regular','{}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1133,'en','wait','to wait','verb','regular','{}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1134,'en','travel','to travel','verb','regular','{}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1135,'en','drive','to drive','verb','irregular','{"preteritum": "drove", "supine": "driven"}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1136,'en','fly','to fly','verb','irregular','{"preteritum": "flew", "supine": "flown"}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1137,'en','swim','to swim','verb','irregular','{"preteritum": "swam", "supine": "swum"}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1138,'en','sing','to sing','verb','irregular','{"preteritum": "sang", "supine": "sung"}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1139,'en','dance','to dance','verb','regular','{}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1140,'en','laugh','to laugh','verb','regular','{}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1141,'en','long','long','adj','regular','{}','long, tall') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1142,'en','short','short','adj','regular','{}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1143,'en','high','high','adj','regular','{}','high, tall') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1144,'en','low','low','adj','regular','{}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1145,'en','heavy','heavy','adj','regular','{}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1146,'en','light','light','adj','regular','{}','light (weight), easy') ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1147,'en','strong','strong','adj','regular','{}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1148,'en','weak','weak','adj','regular','{}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1149,'en','beautiful','beautiful','adj','periphrastic','{}',NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO lexeme (id,lang,lemma,citation,pos,infl_class,tema,note) VALUES (1150,'en','ugly','ugly','adj','regular','{}',NULL) ON CONFLICT (id) DO NOTHING;

-- ---------- word forms (Swedish) ----------
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1001,'indef_sg','pojke'),(1001,'def_sg','pojken'),(1001,'indef_pl','pojkar'),(1001,'def_pl','pojkarna') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1002,'indef_sg','flicka'),(1002,'def_sg','flickan'),(1002,'indef_pl','flickor'),(1002,'def_pl','flickorna') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1003,'indef_sg','mamma'),(1003,'def_sg','mamman'),(1003,'indef_pl','mammor'),(1003,'def_pl','mammorna') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1004,'indef_sg','pappa'),(1004,'def_sg','pappan'),(1004,'indef_pl','pappor'),(1004,'def_pl','papporna') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1005,'indef_sg','bror'),(1005,'def_sg','brodern'),(1005,'indef_pl','bröder'),(1005,'def_pl','bröderna') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1006,'indef_sg','syster'),(1006,'def_sg','systern'),(1006,'indef_pl','systrar'),(1006,'def_pl','systrarna') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1007,'indef_sg','rum'),(1007,'def_sg','rummet'),(1007,'indef_pl','rum'),(1007,'def_pl','rummen') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1008,'indef_sg','kök'),(1008,'def_sg','köket'),(1008,'indef_pl','kök'),(1008,'def_pl','köken') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1009,'indef_sg','säng'),(1009,'def_sg','sängen'),(1009,'indef_pl','sängar'),(1009,'def_pl','sängarna') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1010,'indef_sg','klocka'),(1010,'def_sg','klockan'),(1010,'indef_pl','klockor'),(1010,'def_pl','klockorna') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1011,'indef_sg','nyckel'),(1011,'def_sg','nyckeln'),(1011,'indef_pl','nycklar'),(1011,'def_pl','nycklarna') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1012,'indef_sg','väska'),(1012,'def_sg','väskan'),(1012,'indef_pl','väskor'),(1012,'def_pl','väskorna') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1013,'indef_sg','skola'),(1013,'def_sg','skolan'),(1013,'indef_pl','skolor'),(1013,'def_pl','skolorna') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1014,'indef_sg','arbete'),(1014,'def_sg','arbetet'),(1014,'indef_pl','arbeten'),(1014,'def_pl','arbetena') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1015,'indef_sg','affär'),(1015,'def_sg','affären'),(1015,'indef_pl','affärer'),(1015,'def_pl','affärerna') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1016,'indef_sg','tåg'),(1016,'def_sg','tåget'),(1016,'indef_pl','tåg'),(1016,'def_pl','tågen') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1017,'indef_sg','flygplan'),(1017,'def_sg','flygplanet'),(1017,'indef_pl','flygplan'),(1017,'def_pl','flygplanen') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1018,'indef_sg','gata'),(1018,'def_sg','gatan'),(1018,'indef_pl','gator'),(1018,'def_pl','gatorna') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1019,'indef_sg','sol'),(1019,'def_sg','solen'),(1019,'indef_pl','solar'),(1019,'def_pl','solarna') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1020,'indef_sg','måne'),(1020,'def_sg','månen'),(1020,'indef_pl','månar'),(1020,'def_pl','månarna') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1021,'infinitive','komma'),(1021,'present','kommer'),(1021,'preteritum','kom'),(1021,'supine','kommit') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1022,'infinitive','ge'),(1022,'present','ger'),(1022,'preteritum','gav'),(1022,'supine','gett') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1023,'infinitive','ta'),(1023,'present','tar'),(1023,'preteritum','tog'),(1023,'supine','tagit') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1024,'infinitive','se'),(1024,'present','ser'),(1024,'preteritum','såg'),(1024,'supine','sett') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1025,'infinitive','höra'),(1025,'present','hör'),(1025,'preteritum','hörde'),(1025,'supine','hört') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1026,'infinitive','känna'),(1026,'present','känner'),(1026,'preteritum','kände'),(1026,'supine','känt') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1027,'infinitive','tänka'),(1027,'present','tänker'),(1027,'preteritum','tänkte'),(1027,'supine','tänkt') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1028,'infinitive','veta'),(1028,'present','vet'),(1028,'preteritum','visste'),(1028,'supine','vetat') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1029,'infinitive','förstå'),(1029,'present','förstår'),(1029,'preteritum','förstod'),(1029,'supine','förstått') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1030,'infinitive','fråga'),(1030,'present','frågar'),(1030,'preteritum','frågade'),(1030,'supine','frågat') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1031,'infinitive','svara'),(1031,'present','svarar'),(1031,'preteritum','svarade'),(1031,'supine','svarat') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1032,'infinitive','hjälpa'),(1032,'present','hjälper'),(1032,'preteritum','hjälpte'),(1032,'supine','hjälpt') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1033,'infinitive','vänta'),(1033,'present','väntar'),(1033,'preteritum','väntade'),(1033,'supine','väntat') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1034,'infinitive','resa'),(1034,'present','reser'),(1034,'preteritum','reste'),(1034,'supine','rest') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1035,'infinitive','köra'),(1035,'present','kör'),(1035,'preteritum','körde'),(1035,'supine','kört') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1036,'infinitive','flyga'),(1036,'present','flyger'),(1036,'preteritum','flög'),(1036,'supine','flugit') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1037,'infinitive','simma'),(1037,'present','simmar'),(1037,'preteritum','simmade'),(1037,'supine','simmat') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1038,'infinitive','sjunga'),(1038,'present','sjunger'),(1038,'preteritum','sjöng'),(1038,'supine','sjungit') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1039,'infinitive','dansa'),(1039,'present','dansar'),(1039,'preteritum','dansade'),(1039,'supine','dansat') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1040,'infinitive','skratta'),(1040,'present','skrattar'),(1040,'preteritum','skrattade'),(1040,'supine','skrattat') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1041,'utrum','lång'),(1041,'neutrum','långt'),(1041,'plural','långa') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1042,'utrum','kort'),(1042,'neutrum','kort'),(1042,'plural','korta') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1043,'utrum','hög'),(1043,'neutrum','högt'),(1043,'plural','höga') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1044,'utrum','låg'),(1044,'neutrum','lågt'),(1044,'plural','låga') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1045,'utrum','tung'),(1045,'neutrum','tungt'),(1045,'plural','tunga') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1046,'utrum','lätt'),(1046,'neutrum','lätt'),(1046,'plural','lätta') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1047,'utrum','stark'),(1047,'neutrum','starkt'),(1047,'plural','starka') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1048,'utrum','svag'),(1048,'neutrum','svagt'),(1048,'plural','svaga') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1049,'utrum','vacker'),(1049,'neutrum','vackert'),(1049,'plural','vackra') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1050,'utrum','ful'),(1050,'neutrum','fult'),(1050,'plural','fula') ON CONFLICT (lexeme_id,form_type) DO NOTHING;

-- ---------- word forms (English) ----------
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1101,'sg','boy'),(1101,'pl','boys') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1102,'sg','girl'),(1102,'pl','girls') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1103,'sg','mum'),(1103,'pl','mums') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1104,'sg','dad'),(1104,'pl','dads') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1105,'sg','brother'),(1105,'pl','brothers') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1106,'sg','sister'),(1106,'pl','sisters') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1107,'sg','room'),(1107,'pl','rooms') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1108,'sg','kitchen'),(1108,'pl','kitchens') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1109,'sg','bed'),(1109,'pl','beds') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1110,'sg','clock'),(1110,'pl','clocks') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1111,'sg','key'),(1111,'pl','keys') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1112,'sg','bag'),(1112,'pl','bags') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1113,'sg','school'),(1113,'pl','schools') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1114,'sg','work'),(1114,'pl','works') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1115,'sg','shop'),(1115,'pl','shops') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1116,'sg','train'),(1116,'pl','trains') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1117,'sg','aeroplane'),(1117,'pl','aeroplanes') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1118,'sg','street'),(1118,'pl','streets') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1119,'sg','sun'),(1119,'pl','suns') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1120,'sg','moon'),(1120,'pl','moons') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1121,'infinitive','come'),(1121,'present_3sg','comes'),(1121,'preteritum','came'),(1121,'supine','come'),(1121,'present_participle','coming') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1122,'infinitive','give'),(1122,'present_3sg','gives'),(1122,'preteritum','gave'),(1122,'supine','given'),(1122,'present_participle','giving') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1123,'infinitive','take'),(1123,'present_3sg','takes'),(1123,'preteritum','took'),(1123,'supine','taken'),(1123,'present_participle','taking') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1124,'infinitive','see'),(1124,'present_3sg','sees'),(1124,'preteritum','saw'),(1124,'supine','seen'),(1124,'present_participle','seeing') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1125,'infinitive','hear'),(1125,'present_3sg','hears'),(1125,'preteritum','heard'),(1125,'supine','heard'),(1125,'present_participle','hearing') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1126,'infinitive','feel'),(1126,'present_3sg','feels'),(1126,'preteritum','felt'),(1126,'supine','felt'),(1126,'present_participle','feeling') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1127,'infinitive','think'),(1127,'present_3sg','thinks'),(1127,'preteritum','thought'),(1127,'supine','thought'),(1127,'present_participle','thinking') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1128,'infinitive','know'),(1128,'present_3sg','knows'),(1128,'preteritum','knew'),(1128,'supine','known'),(1128,'present_participle','knowing') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1129,'infinitive','understand'),(1129,'present_3sg','understands'),(1129,'preteritum','understood'),(1129,'supine','understood'),(1129,'present_participle','understanding') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1130,'infinitive','ask'),(1130,'present_3sg','asks'),(1130,'preteritum','asked'),(1130,'supine','asked'),(1130,'present_participle','asking') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1131,'infinitive','answer'),(1131,'present_3sg','answers'),(1131,'preteritum','answered'),(1131,'supine','answered'),(1131,'present_participle','answering') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1132,'infinitive','help'),(1132,'present_3sg','helps'),(1132,'preteritum','helped'),(1132,'supine','helped'),(1132,'present_participle','helping') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1133,'infinitive','wait'),(1133,'present_3sg','waits'),(1133,'preteritum','waited'),(1133,'supine','waited'),(1133,'present_participle','waiting') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1134,'infinitive','travel'),(1134,'present_3sg','travels'),(1134,'preteritum','travelled'),(1134,'supine','travelled'),(1134,'present_participle','travelling') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1135,'infinitive','drive'),(1135,'present_3sg','drives'),(1135,'preteritum','drove'),(1135,'supine','driven'),(1135,'present_participle','driving') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1136,'infinitive','fly'),(1136,'present_3sg','flies'),(1136,'preteritum','flew'),(1136,'supine','flown'),(1136,'present_participle','flying') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1137,'infinitive','swim'),(1137,'present_3sg','swims'),(1137,'preteritum','swam'),(1137,'supine','swum'),(1137,'present_participle','swimming') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1138,'infinitive','sing'),(1138,'present_3sg','sings'),(1138,'preteritum','sang'),(1138,'supine','sung'),(1138,'present_participle','singing') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1139,'infinitive','dance'),(1139,'present_3sg','dances'),(1139,'preteritum','danced'),(1139,'supine','danced'),(1139,'present_participle','dancing') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1140,'infinitive','laugh'),(1140,'present_3sg','laughs'),(1140,'preteritum','laughed'),(1140,'supine','laughed'),(1140,'present_participle','laughing') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1141,'base','long'),(1141,'comparative','longer'),(1141,'superlative','longest') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1142,'base','short'),(1142,'comparative','shorter'),(1142,'superlative','shortest') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1143,'base','high'),(1143,'comparative','higher'),(1143,'superlative','highest') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1144,'base','low'),(1144,'comparative','lower'),(1144,'superlative','lowest') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1145,'base','heavy'),(1145,'comparative','heavier'),(1145,'superlative','heaviest') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1146,'base','light'),(1146,'comparative','lighter'),(1146,'superlative','lightest') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1147,'base','strong'),(1147,'comparative','stronger'),(1147,'superlative','strongest') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1148,'base','weak'),(1148,'comparative','weaker'),(1148,'superlative','weakest') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1149,'base','beautiful'),(1149,'comparative','more beautiful'),(1149,'superlative','most beautiful') ON CONFLICT (lexeme_id,form_type) DO NOTHING;
INSERT INTO word_form (lexeme_id,form_type,form) VALUES (1150,'base','ugly'),(1150,'comparative','uglier'),(1150,'superlative','ugliest') ON CONFLICT (lexeme_id,form_type) DO NOTHING;

-- ---------- translations (undirected, sv_id < en_id; pos-aligned) ----------
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1001,1101) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1002,1102) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1003,1103) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1004,1104) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1005,1105) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1006,1106) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1007,1107) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1008,1108) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1009,1109) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1010,1110) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1011,1111) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1012,1112) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1013,1113) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1014,1114) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1015,1115) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1016,1116) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1017,1117) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1018,1118) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1019,1119) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1020,1120) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1021,1121) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1022,1122) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1023,1123) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1024,1124) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1025,1125) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1026,1126) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1027,1127) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1028,1128) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1029,1129) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1030,1130) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1031,1131) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1032,1132) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1033,1133) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1034,1134) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1035,1135) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1036,1136) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1037,1137) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1038,1138) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1039,1139) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1040,1140) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1041,1141) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1042,1142) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1043,1143) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1044,1144) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1045,1145) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1046,1146) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1047,1147) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1048,1148) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1049,1149) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;
INSERT INTO translation (lexeme_a,lexeme_b) VALUES (1050,1150) ON CONFLICT (lexeme_a,lexeme_b) DO NOTHING;

-- ---------- lists ----------
INSERT INTO list (id,name,target_lang,user_id,allowed_exercises) VALUES (100,'Swedish first 50','sv',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO list (id,name,target_lang,user_id,allowed_exercises) VALUES (101,'Basic nouns','sv',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO list (id,name,target_lang,user_id,allowed_exercises) VALUES (102,'Basic verbs','sv',NULL,NULL) ON CONFLICT (id) DO NOTHING;

-- ---------- list items ----------
-- Swedish first 50: all 50
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1001,1) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1002,2) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1003,3) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1004,4) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1005,5) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1006,6) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1007,7) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1008,8) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1009,9) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1010,10) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1011,11) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1012,12) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1013,13) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1014,14) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1015,15) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1016,16) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1017,17) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1018,18) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1019,19) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1020,20) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1021,21) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1022,22) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1023,23) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1024,24) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1025,25) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1026,26) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1027,27) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1028,28) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1029,29) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1030,30) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1031,31) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1032,32) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1033,33) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1034,34) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1035,35) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1036,36) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1037,37) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1038,38) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1039,39) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1040,40) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1041,41) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1042,42) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1043,43) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1044,44) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1045,45) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1046,46) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1047,47) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1048,48) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1049,49) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (100,1050,50) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
-- Basic nouns: 20
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (101,1001,1) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (101,1002,2) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (101,1003,3) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (101,1004,4) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (101,1005,5) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (101,1006,6) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (101,1007,7) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (101,1008,8) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (101,1009,9) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (101,1010,10) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (101,1011,11) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (101,1012,12) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (101,1013,13) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (101,1014,14) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (101,1015,15) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (101,1016,16) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (101,1017,17) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (101,1018,18) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (101,1019,19) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (101,1020,20) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
-- Basic verbs: 20
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (102,1021,1) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (102,1022,2) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (102,1023,3) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (102,1024,4) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (102,1025,5) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (102,1026,6) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (102,1027,7) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (102,1028,8) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (102,1029,9) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (102,1030,10) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (102,1031,11) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (102,1032,12) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (102,1033,13) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (102,1034,14) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (102,1035,15) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (102,1036,16) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (102,1037,17) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (102,1038,18) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (102,1039,19) ON CONFLICT (list_id,lexeme_id) DO NOTHING;
INSERT INTO list_item (list_id,lexeme_id,position) VALUES (102,1040,20) ON CONFLICT (list_id,lexeme_id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('lexeme','id'), (SELECT max(id) FROM lexeme));
SELECT setval(pg_get_serial_sequence('list','id'),   (SELECT max(id) FROM list));
COMMIT;
