-- =============================================================
--  wipe_except_basic.sql — delete everything EXCEPT the "basic" data
--  (language, account) that seed_base.sql provides.
--
--  Truncates all catalog/content tables (lexeme, word_form, translation,
--  list, list_item) AND all user activity/enrollment tables (attempt,
--  sessions, list_progress, user_list). language and account are left
--  untouched.
--
--  Unlike clear_user_activity.sql (keeps catalog data - lexeme, word_form,
--  translation, list, list_item - intact, only clears activity) and
--  wipe_all.sql (empties language/account too), this is "back to just the
--  base accounts, no words/lists/history at all". Run seed_base.sql first if
--  language/account aren't already populated; follow with a content seed
--  (02_seed.sql / seed_first50.sql) to repopulate the catalog.
--
--  RESTART IDENTITY resets every bigint GENERATED BY DEFAULT AS IDENTITY
--  sequence in the truncated tables back to its start.
-- =============================================================
BEGIN;

TRUNCATE TABLE
  attempt, sessions, list_progress, user_list,
  list_item, list, translation, word_form, lexeme
  RESTART IDENTITY CASCADE;

COMMIT;
