-- =============================================================
--  wipe_all.sql — delete ALL data (catalog + user data), schema stays.
--  Unlike clear_user_activity.sql (clears activity but keeps accounts/
--  catalog) and wipe_except_basic.sql (keeps language/account), this empties
--  every table, including language and account. Re-run seed_base.sql (then
--  a content seed, e.g. 02_seed.sql / seed_first50.sql) afterwards to
--  repopulate, or leave it blank.
--
--  RESTART IDENTITY resets every bigint GENERATED BY DEFAULT AS IDENTITY
--  sequence back to its start, so a fresh seed can insert with the same
--  explicit ids it originally used.
-- =============================================================
BEGIN;

TRUNCATE TABLE
  attempt, sessions, list_progress, user_list, account,
  list_item, list, translation, word_form, lexeme, language
  RESTART IDENTITY CASCADE;

COMMIT;
